-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "2560x1600@60.01", position = "0x0", scale = 1.00 })
hl.monitor({ output = "DP-2", mode = "2560x1440@120.00", position = "-2560x0", scale = 1.00 })
