color0 #34251e
color1 #fd4663
color2 #e48f67
color3 #d6c15c
color4 #abcc66
color5 #ecaf93
color6 #e9da96
color7 #f3f2f2
color8 #716761
color9 #fd4663
color10 #e48f67
color11 #d6c15c
color12 #abcc66
color13 #ecaf93
color14 #e9da96
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #271c16
background            #271c16
foreground            #f3f2f2
selection_foreground  #b6b1af
selection_background  #34251e
active_border_color   #e48f67
inactive_border_color #412e25
url_color             #e48f67

active_tab_foreground   #251c18
active_tab_background   #e48f67
inactive_tab_foreground #b6b1af
inactive_tab_background #412e25
cursor_trail_color      #b6b1af
