color0 #1e2634
color1 #fd4663
color2 #6795e4
color3 #d65f5c
color4 #a968ce
color5 #93b3ec
color6 #e99896
color7 #f2f2f3
color8 #626771
color9 #fd4663
color10 #6795e4
color11 #d65f5c
color12 #a968ce
color13 #93b3ec
color14 #e99896
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #161c27
background            #161c27
foreground            #f2f2f3
selection_foreground  #afb1b6
selection_background  #1e2634
active_border_color   #6795e4
inactive_border_color #252f41
url_color             #6795e4

active_tab_foreground   #181d25
active_tab_background   #6795e4
inactive_tab_foreground #afb1b6
inactive_tab_background #252f41
cursor_trail_color      #afb1b6
